name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.9.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get commit messages
        id: commits
        run: |
          echo "messages=$(git log --pretty=format:'* %s' -n 10)" >> $GITHUB_ENV

      - name: Get version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_ENV

  publish-tag:
    runs-on: ubuntu-latest
    needs: publish-npm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create GitHub tag
        run: |
          VERSION=${{ env.version }}
          IMAGE_URL="https://example.com/image.png"
          COMMIT_MESSAGES=${{ env.messages }}
          TAG_MESSAGE="![Image]($IMAGE_URL)\n\n## Release Notes\n\n${COMMIT_MESSAGES}"
          git tag -a "v$VERSION" -m "$TAG_MESSAGE"
          git push origin "v$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}